### ISSUE TITLE
CLI version info outdated (2.1.0 instead of 2.1.2)

### ISSUE THREAD

**Issue by ThiloLutz** [daisy/pipeline-cli-go#29]
The version information is outdated in version 2.1.1 and 2.1.2. This is the case both in the standalone version and in the versions packaged with the DAISY Pipeline 2 v.1.12.1 and 1.13.0, respectively.

**Comment by bertfrees** [comment]
@ThiloLutz Thanks for pointing this out. I didn't realize the version number is hard-coded in Go.

**Comment by bertfrees** [comment]
Fixed in 65750286a01a64e2c9d259bb052c56e524a01460
